#!/data/data/com.termux/files/usr/bin/bash
## Author : Asif Javed
## Email  : lovehacker966@gmail.com
## Github : @lovehackerAsif
## Reddit : lovehacker
 
#colors
R='\033[1;31m'
B='\033[1;34m'
C='\033[0;36m'
G='\033[1;32m'
W='\033[1;37m'
Y='\033[1;33m'
 
DIR="$(pwd)"
 
echo
echo -e $C"   ┈┈┈┈╱▔▔▔▔╲┈┈┈┈ "
echo -e $C"   ┈┈┈▕▕╲┊┊╱▏▏┈┈┈ "
echo -e $C"   ┈┈┈▕▕▂╱╲▂▏▏┈┈┈ "
echo -e $C"   ┈┈┈┈╲┊┊┊┊╱┈┈┈┈ "
echo -e $C"   ┈┈┈┈▕╲▂▂╱▏┈┈┈┈ "
echo -e $C"   ╱▔▔▔▔┊┊┊┊▔▔▔▔╲ "
echo
 
echo -e $R"   [*] Installing BlackMafia-Style..."
echo
echo -e $G"   [*] Setting Up The Program..."
echo
 
if [ ! -d $HOME/.termux ]; then
mkdir $HOME/.termux
fi
 
mv $DIR/data.tar.gz $PREFIX/share
cd $PREFIX/share
echo -e $R"   [*] Extracting Files..."$Y
echo
tar -xhf data.tar.gz
chmod +x BlackMafia-Style/theme
ln -s $PREFIX/share/BlackMafia-Style/theme $PREFIX/bin/BlackMafia-Style
rm $PREFIX/share/data.tar.gz
termux-reload-settings
echo -e $G"   [*] Setup Completed."
echo
echo -e $B"   [*] Typing 'BlackMafia-Style'."
echo -e $B"   [*] WhatsApp Num 03094161457."
echo
echo -e $R"   [*] Developed By$lovehacker."
echo
 
 
